[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
axum = "0.7.4"
dotenv = "0.15.0"
env_logger = "0.11.1"
hyper = "1.1.0"
json = "0.12.4"
log = "0.4.20"
postgres = "0.19.7"
serde = "1.0.196"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls", "macros", "migrate"] }
sqlx-core = "0.7.3"
sqlx-sqlite = "0.7.3"
tokio ={ version="1.36.0", features = ["full"] }
uuid = "1.7.0"
