version: "3.8"

services:
  # Main Database
  db:
    image: postgres:16.0
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - zenote_db:/var/lib/postgresql/data
    networks:
      - web

  # Test Database
  db-test:
    image: postgres:16.0
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
    ports:
      - "5433:5432"
    volumes:
      - zenote_db_test:/var/lib/postgresql/data
    networks:
      - web

volumes:
  zenote_db:
  zenote_db_test:

networks:
  web:
    driver: bridge
