version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - zenote_db:/var/lib/postgresql/data

  # Test database
  db-test:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
    ports:
      - "5433:5432"
    volumes:
      - zenote_db_test:/var/lib/postgresql/data

volumes:
  zenote_db:
  zenote_db_test:
